# headings

## sub-headings

normal text
- vrvf
- fvfv

In [2]:
import numpy as np

In [3]:
list1 = [10, 20, 30]
list1

[10, 20, 30]

In [4]:
arr1 = np.array(list1)
arr1

array([10, 20, 30])

In [5]:
type(list1)

list

In [6]:
type(arr1)

numpy.ndarray

In [24]:
arr2 = np.arrange(10, 20, 2)
arr2

AttributeError: module 'numpy' has no attribute 'arrange'

In [9]:
list2 = [40, 50, 60]
list2

[40, 50, 60]

In [10]:
list3 = [list1, list2]
list3

[[10, 20, 30], [40, 50, 60]]

In [12]:
arr3 = np.array(list3)
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [14]:
arr3.shape

(2, 3)

In [71]:
arr4 = np.array([[[1,2,3],[4,5,6]],
                [[7,8,9],[2,3,4]]])
arr4

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [2, 3, 4]]])

In [18]:
arr4.shape

(2, 2, 3)

In [19]:
list1 * 3

[10, 20, 30, 10, 20, 30, 10, 20, 30]

In [20]:
arr1 * 3

array([30, 60, 90])

In [21]:
arr4 * 3

array([[[ 3,  6,  9],
        [12, 15, 18]],

       [[21, 24, 27],
        [ 6,  9, 12]]])

In [22]:
arr2 = np.array(list2)
arr2

array([40, 50, 60])

In [23]:
arr1 * arr2

array([ 400, 1000, 1800])

In [25]:
arr1 * arr4

array([[[ 10,  40,  90],
        [ 40, 100, 180]],

       [[ 70, 160, 270],
        [ 20,  60, 120]]])

# Task 1

In [32]:
one_D = [1,2,3,4,5,6,7,8,9,10,11,12]

In [33]:
one_Darr = np.array(one_D)

In [34]:
one_Darr.shape

(12,)

In [39]:
two_D1 = [1, 2, 3, 4]

In [37]:
two_D2 = [1, 2, 3, 4]

In [38]:
two_D3 = [1, 2, 3, 4]

In [44]:
two_D4 = [two_D1, two_D2, two_D3]

In [45]:
twoDarr = np.array(two_D4)

In [46]:
twoDarr.shape

(3, 4)

In [52]:
ar = np.array([[[1,2,3,4],[4,5,6,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]],
                [[7,8,9,4],[2,3,4,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
ar

array([[[1, 2, 3, 4],
        [4, 5, 6, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[7, 8, 9, 4],
        [2, 3, 4, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [51]:
ar.shape

(2, 5, 4)

In [53]:
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [58]:
arr3[1, 2]

60

In [59]:
arr3[1, :]

array([40, 50, 60])

In [60]:
arr3[:,1]

array([20, 50])

In [61]:
arr3.sum()

210

In [62]:
arr3.sum(0)

array([50, 70, 90])

In [63]:
arr3.sum(1)

array([ 60, 150])

In [64]:
arr3.max()

60

In [65]:
arr1

array([10, 20, 30])

In [72]:
for x in arr3:
    print(x)

[10 20 30]
[40 50 60]


In [74]:
for x in np.nditer(arr4):
    print(x)

1
2
3
4
5
6
7
8
9
2
3
4
